# Generated by Django 2.1.7 on 2019-04-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_team_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, height_field=100, upload_to='img', width_field=100),
        ),
    ]
