# Generated by Django 2.1.7 on 2019-04-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190410_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
