# Generated by Django 2.1.7 on 2019-04-10 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190410_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
