# Generated by Django 2.1.7 on 2019-04-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190411_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/Project'),
        ),
    ]
