# Generated by Django 2.1.7 on 2019-04-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
